### PR TITLE
Switch to NATO ports on the mask

### PR DESCRIPTION
**Pull request by scottyallen**

### CODE REVIEW

**Comment by stephen304** [comment]
I don't see any issues with this as it is. The ports are at slightly different heights, not sure if that's intentional, but looks good :+1:

**Comment by stephen304** [comment]
Only other note, I've been thinking about what orientation would be most conducive to printing. My non-evidence-based opinion is that it would probably be good to have all the threaded ports parallel to the z plane, maybe face down on the print bed (probably would require some supports on the inside, probably wouldn't be too bad to clean up) or pointed up. In order to get that alignment you could have the ports one above another in the center angled somewhat downward relative to the mask when worn (so that the mask top is pointed diagonally upwards when placed ports down on the bed) which also helps to make it fit on the print bed.

I don't mean for this to be actionable right now but just some thoughts

**Comment by scottyallen** [comment]
> I don't see any issues with this as it is. The ports are at slightly different heights, not sure if that's intentional, but looks good 👍

Yeah, I was wondering that.  The mask is slightly asymmetrical, which I think is mostly due to the asymmetry of the scan of my head (and possibly my head being asymmetrical).  I fiddled with it a bit, but I'll take another look though, and see if I can make the ports more the same height.

**Comment by scottyallen** [comment]
> Only other note, I've been thinking about what orientation would be most conducive to printing. My non-evidence-based opinion is that it would probably be good to have all the threaded ports parallel to the z plane, maybe face down on the print bed (probably would require some supports on the inside, probably wouldn't be too bad to clean up) or pointed up. In order to get that alignment you could have the ports one above another in the center angled somewhat downward relative to the mask when worn (so that the mask top is pointed diagonally upwards when placed ports down on the bed) which also helps to make it fit on the print bed.
> 
> I don't mean for this to be actionable right now but just some thoughts

Hrm, interesting.  I suspect that would make the print quite tall though, which probably makes the print time longer?

**Comment by stephen304** [comment]
> Hrm, interesting. I suspect that would make the print quite tall though, which probably makes the print time longer?

@scottyallen 

The only difference the orientation could make is if a specific orientation requires more supports, since FDM print times depend mostly on the total amount of material unlike SLA which is purely based on print height. For me I would have to orient the mask slightly diagonal anyways because the top to bottom length can exceed the mk3s bed width in the default orientation. The variance seems to be between 2 days 6 hours and 2 days 10 hours. I've attached a screenshot of a slightly diagonal orientation that's 2d6h which is how I would probably print it. I think I found an orientation that was as low as 2d, but I can't seem to find that again. Not suggesting this is the best orientation.

image

**Comment by scottyallen** [comment]
@stephen304 I updated the port position to hopefully be more symmetrical.

**Comment by scottyallen** [comment]
As for print position and time, what you're saying makes sense.  Maybe we should experiment with what you're saying about the ports being centered vertically.  And maybe put the front of the ports on the same plane, so that they can both sit flush with the printer bed?

I'd suggest we do that in a separate pull request though, if that's cool with you?

**Review by stephen304 — APPROVED** [review]

**Pull request merged**
